import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)
const state={
    shopLists: [
        {   id:1,
            src: require("../../image/recommand0.jpg"),
            title: "银离子速干致冷抗菌T",
            desc: " 抗菌除臭 ",
            price: 19.99,
        },
        {id:2,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米",
            desc: " 五谷稻米 ",
            price: 29.99,
        },
        {id:3,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 纯真酸奶 ",
            price: 39.99,
        },
        {id:4,
            src: require("../../image/recommand3.jpg"),
            title: "驱鼠黑科技空间驱鼠器",
            desc: " 国际领先 ",
            price: 199.99,
        },
        {id:5,
            src: require("../../image/recommand4.jpg"),
            title: "多功能迷你剃须刀",
            desc: " 值得拥有 ",
            price: 49.99,
        },
        {id:6,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:7,
            src: require("../../image/recommand3.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:8,
            src: require("../../image/recommand0.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:9,
            src: require("../../image/recommand4.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:10,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:11,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:12,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:13,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:14,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:15,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:16,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:17,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:18,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:19,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:20,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:21,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:22,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:23,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:24,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:25,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:26,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:27,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:28,
            src: require("../../image/recommand3.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        },
        {id:29,
            src: require("../../image/recommand1.jpg"),
            title: "纯天然五谷香米T",
            desc: " 抗菌除臭 ",
            price: 49.99,
        },
        {id:30,
            src: require("../../image/recommand2.jpg"),
            title: "银离子高温杀菌酸奶",
            desc: " 抗菌除臭 ",
            price: 59.99,
        }
    ],
    added:[]
}
const getters={
    shopLists:(state)=>state.shopLists,
    added:state=>state.added
}
const mutations={
    add(state,{item}){
        let record=state.added.find(n=>n.id==item.id);
        if(!record){
            state.added.push(item)
        }
    },
    subtract(state,{index}){
        state.added.splice(index,1)
    }
}
const actions={}
export default new Vuex.Store({
    state,
    getters,
    mutations,
    actions
})